[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--include=dev"
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "http://activemedia.runasp.net/api/:splat"
  status = 200
  force = true
