// <auto-generated />
using System;
using ActiveMedia.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActiveMedia.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519000215_AddRolePermissionsTable")]
    partial class AddRolePermissionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActiveMedia.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "logo_url");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "manager_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("TestimonialRole")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "testimonial_role");

                    b.Property<string>("TestimonialText")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "testimonial_text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasAnnotation("Relational:JsonPropertyName", "clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(3090),
                            LogoUrl = "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=300",
                            ManagerName = "Ahmed Alabbar",
                            Name = "Emaar Properties",
                            TestimonialRole = "Marketing Director",
                            TestimonialText = "Active Media delivered outstanding visual storytelling that transformed our marketing campaigns."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(3184),
                            LogoUrl = "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=300",
                            ManagerName = "Khalid Al-Falih",
                            Name = "Saudi Aramco",
                            TestimonialRole = "VP Communications",
                            TestimonialText = "Professionalism and premium quality at every step of production. Highly recommended."
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "full_name");

                    b.Property<string>("Interest")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "interest");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_read");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.Property<string>("ProjectDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "project_details");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "image_urls");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("VimeoId")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "vimeo_id");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Category = "video",
                            ClientId = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(4845),
                            Description = "A cinematic documentary exploring groundbreaking architectural marvels and sustainable smart cities.",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format\\u0026fit=crop\\u0026q=80\\u0026w=1600\",\"https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format\\u0026fit=crop\\u0026q=80\\u0026w=1600\",\"https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format\\u0026fit=crop\\u0026q=80\\u0026w=1600\"]",
                            Tags = "[\"4K Video\",\"Drone\",\"Cinematography\",\"Architectural\"]",
                            Title = "The Future of Urban Living",
                            VimeoId = "824804225",
                            Year = "2025"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Category = "branding",
                            ClientId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(4940),
                            Description = "Comprehensive brand identity overhaul and corporate reveal video highlighting clean energy transitions.",
                            ImageUrls = "[\"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format\\u0026fit=crop\\u0026q=80\\u0026w=1600\",\"https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format\\u0026fit=crop\\u0026q=80\\u0026w=1600\"]",
                            Tags = "[\"Branding\",\"Motion Graphics\",\"Corporate\"]",
                            Title = "Next-Gen Energy Vision",
                            VimeoId = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                            Year = "2026"
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_system");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "permissions");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "role_name");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 797, DateTimeKind.Utc).AddTicks(7336),
                            Description = "صلاحيات المشرف العام الكاملة (إدارة شاملة للنظام)",
                            IsSystem = true,
                            Permissions = "[\"all\"]",
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 797, DateTimeKind.Utc).AddTicks(7466),
                            Description = "إدارة المحتوى والمشاريع والعملاء والرسائل فقط",
                            IsSystem = true,
                            Permissions = "[\"projects_view\",\"projects_edit\",\"projects_delete\",\"clients_view\",\"clients_edit\",\"clients_delete\",\"team_view\",\"team_edit\",\"messages_view\",\"messages_delete\"]",
                            RoleName = "Editor"
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.SiteSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("ManualClientsCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "manual_clients_count");

                    b.Property<string>("ShowreelVimeoId")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "showreel_vimeo_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = "global",
                            ManualClientsCount = 50,
                            ShowreelVimeoId = "https://vimeo.com/824804225",
                            UpdatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(1835)
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "order_index");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Category = "Co-founder",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(5811),
                            ImageUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
                            Name = "Omar Al-Sayed",
                            OrderIndex = 1,
                            Role = "Founder & Executive Producer"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Category = "Leadership",
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(5898),
                            ImageUrl = "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=800",
                            Name = "Sarah Mansour",
                            OrderIndex = 2,
                            Role = "Creative Director"
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 5, 19, 0, 2, 12, 802, DateTimeKind.Utc).AddTicks(588),
                            Email = "admin@activemedia.com",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("ActiveMedia.Api.Models.Project", b =>
                {
                    b.HasOne("ActiveMedia.Api.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
